### ISSUE TITLE
[feat] Publicize.kt 추가 

### ISSUE THREAD

**Issue by jooyyoo** [UnderTheSea-E/UnderTheSea_AOS#2]
### 파일 추가 ###
홍보용 파일  (Publicize)를 추가하긴 했는데,, 어렵군요
그리고 사실 issue 쓰는 방법 익혀보려고 이걸로 기록 남기는 중

**Comment by wyoung163** [comment]
구성 좋아요! 파일 이름은 통일하면 좋으니까 PromotionHelper로 바꾸면 좋을 것 같아
파일 위치는 map 패키지 말고 promotion 패키지를 하나 더 만들어서 그 밑으로 이동하는 걸로 합시다!

**Comment by wyoung163** [comment]
아 그리고 branch도 fearture/promotion으로!

**Comment by jooyyoo** [comment]
branch  추가완료
promotion 패키지 만들기 완료
